services:

  wiemansite:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      PUBLIC_API_BASE_URL: "https://jarnowieman.nl/api"
      PUBLIC_IMAGE_BASE_URL: "https://jarnowieman.nl/assets"