name: Create release

on:
  push:
    branches:
      - master
      - release/*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "Version: $VERSION"
          echo "::set-output name=result::$VERSION"

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: ${{ steps.get_version.outputs.result }}
          prerelease: false
          title: "${{ github.event.repository.name }} v${{ steps.get_version.outputs.result }}"