name: Run tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        # Install rollup manually because of bug with optional dependencies (https://github.com/npm/cli/issues/4828)
        run: npm install && npm install -D @rollup/rollup-linux-x64-gnu && npx playwright install

      - name: Run tests
        run: npm test
        env:
          PUBLIC_API_BASE_URL: ${{ vars.PUBLIC_API_BASE_URL }}
          PUBLIC_IMAGE_BASE_URL: ${{ vars.PUBLIC_IMAGE_BASE_URL }}

      - name: Test docker build
        run: docker build -t test .
