name: Run tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        # Install rollup manually because of bug with optional dependencies (https://github.com/npm/cli/issues/4828)
        run: npm install && npm install -D @rollup/rollup-linux-x64-gnu && npx playwright install

      - name: Run tests
        run: npm test
        env:
          PUBLIC_API_BASE_URL: ${{ vars.PUBLIC_API_BASE_URL }}
          PUBLIC_IMAGE_BASE_URL: ${{ vars.PUBLIC_IMAGE_BASE_URL }}

      - name: Test docker build
        run: docker build -t test .

  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get version from package.json
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "Version: $VERSION"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Check if tag already exists
        run: |
          TAG_EXISTS=$(gh release list --json tagName --jq '.[] | select(.tagName == "${{ env.VERSION }}") | length')
          if [ "$TAG_EXISTS" -gt 0 ]; then
            echo "Tag ${VERSION} already exists. Blocking the PR."
            echo "BLOCK_PR=true" >> $GITHUB_ENV
          else
            echo "Tag ${VERSION} does not exist."
            echo "BLOCK_PR=false" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}

      - name: Block pull request if tag exists
        if: env.BLOCK_PR == 'true'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "Version ${{env.VERSION}} already exists, this will overwrite the existing release. If this is a mistake, please bump the version in package.json."
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
